# Generated by Django 3.0.8 on 2020-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.BigIntegerField()),
                ('permission_name', models.CharField(max_length=64)),
                ('permission_dec', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.BigIntegerField()),
                ('role_name', models.CharField(max_length=64)),
                ('create_time', models.DateField()),
                ('role_dec', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('create_time', models.DateField()),
                ('login_time', models.DateField(null=True)),
                ('last_login_time', models.DateField(null=True)),
                ('login_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.ManyToManyField(to='app.role')),
                ('user_id', models.ManyToManyField(to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='user_permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_type', models.IntegerField()),
                ('permission_id', models.ManyToManyField(to='app.permission')),
                ('user_id', models.ManyToManyField(to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='role_permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_type', models.IntegerField()),
                ('permission_id', models.ManyToManyField(to='app.permission')),
                ('role_id', models.ManyToManyField(to='app.role')),
            ],
        ),
    ]
